name: 🤖 간단 자동매매

on:
  schedule:
    - cron: '30 0 * * 1-5'  # 평일 오전 9시 30분
  workflow_dispatch:

jobs:
  simple-trading:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 🐍 Python 설정
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: 📦 의존성 설치
      run: |
        pip install -r requirements.txt
    
    - name: 🚀 간단 자동매매 실행
      env:
        MOCK_KIS_APP_KEY: ${{ secrets.MOCK_KIS_APP_KEY }}
        MOCK_KIS_APP_SECRET: ${{ secrets.MOCK_KIS_APP_SECRET }}
        MOCK_KIS_ACCOUNT_NUMBER: ${{ secrets.MOCK_KIS_ACCOUNT_NUMBER }}
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        IS_MOCK: true
      run: |
        python src/simple_trader.py
    
    - name: 📋 로그 업로드
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: trading-logs
        path: "*.log" 