name: 🔥 고급 기능 자동화

on:
  schedule:
    - cron: '0 9 * * 1-5'  # 평일 오전 9시
  workflow_dispatch:

jobs:
  # 자동 백테스팅 및 성과 분석
  automated-analysis:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 📊 주간 성과 분석
      run: |
        python scripts/weekly_performance_analysis.py
        python scripts/strategy_optimization.py
    
    - name: 📈 리포트 생성
      run: |
        python scripts/generate_weekly_report.py
    
    - name: 📧 리포트 전송
      env:
        TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
      run: |
        python scripts/send_weekly_report.py

  # 자동 의존성 업데이트
  dependency-update:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    
    - name: 🔄 의존성 업데이트 확인
      run: |
        pip-audit --desc --output=json > security-audit.json
        python scripts/check_dependency_updates.py
    
    - name: 🔧 자동 PR 생성
      if: success()
      uses: peter-evans/create-pull-request@v5
      with:
        title: "🔄 자동 의존성 업데이트"
        body: "보안 및 성능 개선을 위한 의존성 업데이트"
        branch: auto-dependency-update 