# ML+DL+AI 완전자동매매 시스템 백테스트 설정
# 과거 최대치 실전 데이터 (2020-2024)

# 데이터 설정
data:
  path: "data/krx_historical_data.csv"
  start_date: "2020-01-01"
  end_date: "2024-12-31"
  symbols: ["KOSPI"]  # 전체 KOSPI 종목
  timeframe: "1d"

# 전략 설정
strategy:
  name: "AI_Complete_Trading"
  type: "ml_dl_ai_auto"
  
  # ML/DL 모델 설정
  models:
    - name: "random_forest"
      type: "classification"
      params:
        n_estimators: 100
        max_depth: 10
    - name: "neural_network"
      type: "regression"
      params:
        hidden_layers: [100, 50, 25]
        activation: "relu"
    - name: "gradient_boosting"
      type: "classification"
      params:
        n_estimators: 100
        learning_rate: 0.1

  # AI 시장분석 설정
  market_analysis:
    features:
      - "price_momentum"
      - "volume_momentum"
      - "volatility"
      - "market_sentiment"
      - "sector_rotation"
    classification_thresholds:
      day_trading: 0.6
      swing_trading: 0.4
      medium_term: 0.2

  # 자동 전략 선택
  auto_strategy_selection:
    day_trading:
      - "momentum_breakout"
      - "gap_trading"
      - "scalping"
    swing_trading:
      - "mean_reversion"
      - "breakout_follow"
      - "sector_rotation"
    medium_term:
      - "trend_following"
      - "value_investing"
      - "dividend_strategy"

# 실행 설정
execution:
  initial_capital: 10000000  # 1천만원
  commission: 0.0005  # 0.05%
  slippage: 0.0002  # 0.02%
  min_trade_size: 100000  # 10만원
  max_position_size: 0.1  # 10%
  
  # 실전 환경 반영
  market_impact: true
  liquidity_constraints: true
  order_delay: 0.1  # 0.1초

# 리스크 관리
risk_management:
  max_drawdown: 0.15  # 15%
  stop_loss: 0.05  # 5%
  take_profit: 0.15  # 15%
  position_sizing: "kelly_criterion"
  portfolio_diversification: true
  max_correlation: 0.7

# 성능 분석
analysis:
  performance_metrics:
    - "total_return"
    - "annualized_return"
    - "sharpe_ratio"
    - "sortino_ratio"
    - "max_drawdown"
    - "calmar_ratio"
    - "win_rate"
    - "profit_factor"
  
  # 과최적화 검증
  overfitting_tests:
    - "walk_forward_analysis"
    - "monte_carlo_simulation"
    - "stress_testing"
    - "statistical_significance"
  
  # 실전 투입 체크리스트
  viability_checklist:
    - "performance_threshold"
    - "overfitting_detection"
    - "data_leakage_check"
    - "market_realism"
    - "risk_control"
    - "execution_feasibility"
    - "cost_analysis"
    - "liquidity_analysis"
    - "model_interpretability"
    - "monitoring_setup"
    - "compliance_check"

# 로깅 설정
logging:
  level: "INFO"
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  file: "logs/ai_trading_backtest.log"

# 리포트 설정
reporting:
  output_dir: "reports/ai_trading_backtest"
  generate_plots: true
  save_trades: true
  performance_summary: true
  risk_analysis: true
  strategy_analysis: true 