name: CursorRule Quality Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:

jobs:
  quality-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: |
          pip install -r requirements-dev.txt
          python markdown_codeblock_cleaner.py
          black --check .
          mypy --strict .
          flake8 .
          pytest
          pip-audit
